accounts/urls.py
from django.urls import path

from .views import login_view, logout_view, register_view, all_user_view, delete_user_view,detail_user_view, update_user_view#, update_password_view
from .views import update_password_view
from django.views.generic import TemplateView

app_name = 'loginapp'

urlpatterns = [
    path('',TemplateView.as_view(template_name="main.html"), name="main"),
    path('home/',TemplateView.as_view(template_name="home.html"), name="home"),
    path('login/',login_view, name="login"),
    path('logout/',logout_view, name="logout"),
    path('register/',register_view, name="fillintheblank"),
    path('users/', all_user_view, name="users"),
    path('users/<str:id>/',detail_user_view, name="users_detail"),
    path('delete/<str:id>/', delete_user_view, name="delete_user"),
    path('update/<str:id>/', update_user_view, name="update"),
    path('updatep/<int:id>/', update_password_view, name="password"),
]

auth/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='loginapp'))
]
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    {% block content1 %}
        
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/detail.html
{% extends 'base.html' %}

{% block content1 %}

    <div class="alert alert-info">
        <div class="row">
            <div class="col">

                <h1 class="display-5">Username : {{ user.username }}</h1>
                <h4 class="display-5">Firstname : {{ user.first_name }}</h4>
                <h4 class="display-5">Lastname : {{ user.last_name }}</h4>
                <h4 class="display-5">Email : {{ user.email }}</h4>
                <h4 class="display-5">is_staff: {{ user.is_staff }}</h4>
                <h4 class="display-5">is_active: {{ user.is_active }}</h4>
                <h4 class="display-5">is_superuser: {{ user.is_superuser }}</h4>
                <h4 class="display-5">Lastlogin: {{ user.last_login }}</h4>
                <!--<a href="/delete/{{ user.id }}/">-->
                <a href = "{% url 'loginapp:delete_user' user.id %}">
                    <button>Delete</button>
                </a>
                <a href = "{% url 'loginapp:update' user.id %}">
                <!--<a href="/update/{{ user.id }}/">-->
                    <button>Update</button>
                </a>
            </div>


        </div>
    </div>
{% endblock %}

templates/error.html
{% extends 'base.html' %}

{% block content1 %}
    {{ error }}
{% endblock %}

templates/form.html
{%  extends 'base.html' %}
{% block content1 %}
    <div class= "alert alert-info">
    <div class= "col-sm-4 com-sm-offset-4">
    <h1>{{title}}</h1>
     <form class='my-ajax-form' method="post" action="" enctype="multipart/form-data" action='.' data-url='{{ request.build_absolute_uri|safe }}'>
     {% csrf_token %}
     {{ form.as_p|safe }}
        
     <input type="submit" class="btn btn-default" value="{{ title }}"/>
    </form>
    </div>
    </div>

    <script>
    $(document).ready(function(){
        var $myForm = $('.my-ajax-form')
        $myForm.submit(function(event){
            event.preventDefault()
            var $formData = $(this).serialize()
            var $thisURL = $myForm.attr('data-url') || window.location.href // or set your own url
            $.ajax({
                method: "POST",
                url: $thisURL,
                data: $formData,
                success: handleFormSuccess,
                error: handleFormError,
            })
        })

        function handleFormSuccess(data, textStatus, jqXHR){
            console.log(data)
            console.log(textStatus)
            console.log(jqXHR)
            $myForm.reset(); // reset form data
        }

        function handleFormError(jqXHR, textStatus, errorThrown){
            console.log(jqXHR)
            console.log(textStatus)
            console.log(errorThrown)
        }
    })
</script>
{% endblock %}

templates/home.html
{%  extends 'base.html' %}
{% block content1 %}
<div class="alert alert-info">
    User : {{user}}<br/>
    SuperUser : {{user.is_superuser}}<br/>
    Staff : {{user.is_staff}}<br/>
    Active : {{user.is_active}}<br/>

    {% if user.is_staff %}
    <br>
    <!--<a href = "/register/">-->
    <a href="{% url 'loginapp:fillintheblank' %}">
        <button class="btn-default" style="align-self: center">
            Add user
        </button>
    </a>
    <!--<a href = "/users/">-->
    <a href="{% url 'loginapp:users' %}">
        <button class="btn-default" style="align-self: center">
            users
        </button>
    </a>

        <a href="{% url 'loginapp:password' user.id %}">
        <button class="btn-default" style="align-self: center">
            Change Password
        </button>
    </a>


    {% endif %}
</div>

{% endblock %}

templates/list.html
{%  extends 'base.html' %}
{% block content1 %}
    <div class="alert alert-info">
        User : {{ user }}<br/>
        SuperUser : {{ user.is_superuser }}
    </div>

    {% if user.is_staff %}
        <div class="alert alert-success col-3">
            <h1 class="display-4">{{ title }}</h1>

            <div class="row">
                <div class="col">
                    <ul class="list-group">
                        {% for user in users %}
                            <!--<a href="/users/{{ user.id }}/">-->
                                <a href="{% url 'loginapp:users_detail' user.id %}">
                            <li class="list-group-item">{{ user.username }}</li>
                            </a>
                        {% endfor %}
                    </ul>
                </div>
            </div>

    </div>
    {% endif %}
{% endblock %}

templates/main.html
{%  extends 'base.html' %}
{% block content1 %}
<div class="alert alert-info">
    <!--<a href="/login/">-->
    <a href="{% url 'loginapp:login' %}">
        <button class="btn-default" style="align-self: center">
            click here
        </button>
    </a>
</div>
{% endblock %}

templates/user_delete.html
{% extends 'base.html' %}

{% block content1 %}
    <form action="." method="POST">{% csrf_token %}
        <h2>
            Do you want to terminate "{{ user }}"
        </h2>
    <p>
        <input type="submit" value="Yes"/>
        <!--<a href="/users/">-->
            <a href="{% url 'loginapp:users' %}">
            Cancel</a>

    </p>
    </form>
{% endblock %}